name: PlatformIO CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Build firmware into docs/firmware
        run: pio run

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            .pio/build/Cardputer-full/**/*.bin
            .pio/build/Cardputer-full/**/*.hex
            .pio/build/Cardputer-full/**/*.uf2
